version: '3'

services:
  db:
    image: mysql:8
    container_name: db_server
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=django
      - MYSQL_DATABASE=django
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
  web:
    build: .
    container_name: django_server
    restart: always
    entrypoint: python manage.py
    command: runserver 0:8000
    ports:
      - "80:8000"
    depends_on:
      - db